[2022-03-03 13:08:19,303][root][ERROR][main.py><module>] ==> 
Traceback (most recent call last):
  File "../main.py", line 155, in <module>
    model, weights = train(muzero_config, summary_writer, model_path)
  File "/home/game/core/train.py", line 1397, in train
    assert False
AssertionError
