[2022-02-22 01:02:48,030][root][ERROR][main.py><module>] ==> model not found at ./model/model/model_1010000.p
Traceback (most recent call last):
  File "../main.py", line 183, in <module>
    assert os.path.exists(model_path), 'model not found at {}'.format(model_path)
AssertionError: model not found at ./model/model/model_1010000.p
