[2021-12-22 15:20:45,749][root][ERROR][main.py><module>] ==> could not broadcast input array from shape (256,6,785) into shape (256)
Traceback (most recent call last):
  File "../main.py", line 148, in <module>
    model, weights = train(muzero_config, summary_writer, model_path)
  File "/home/game/revert/lsy/lst_best_confirm_copy/HanabiZero/core/train.py", line 1431, in train
    final_weights = _train(model, target_model, latest_model, config, storage, replay_buffer, batch_storage, summary_writer)
  File "/home/game/revert/lsy/lst_best_confirm_copy/HanabiZero/core/train.py", line 1331, in _train
    log_data = update_weights(model, batch, optimizer, replay_buffer, config, scaler, True)
  File "/home/game/revert/lsy/lst_best_confirm_copy/HanabiZero/core/train.py", line 703, in update_weights
    sanity_check(batch,n[idx])
  File "/home/game/revert/lsy/lst_best_confirm_copy/HanabiZero/core/train.py", line 691, in sanity_check
    arr=np.array(arr)
ValueError: could not broadcast input array from shape (256,6,785) into shape (256)
