[2021-12-22 14:50:35,492][root][ERROR][main.py><module>] ==> could not broadcast input array from shape (256,6,785) into shape (256)
Traceback (most recent call last):
  File "../main.py", line 148, in <module>
    model, weights = train(muzero_config, summary_writer, model_path)
  File "/home/game/revert/lsy/lst_best_confirm_copy/HanabiZero/core/train.py", line 1428, in train
    final_weights = _train(model, target_model, latest_model, config, storage, replay_buffer, batch_storage, summary_writer)
  File "/home/game/revert/lsy/lst_best_confirm_copy/HanabiZero/core/train.py", line 1328, in _train
    log_data = update_weights(model, batch, optimizer, replay_buffer, config, scaler, True)
  File "/home/game/revert/lsy/lst_best_confirm_copy/HanabiZero/core/train.py", line 700, in update_weights
    sanity_check(batch,n[idx])
  File "/home/game/revert/lsy/lst_best_confirm_copy/HanabiZero/core/train.py", line 691, in sanity_check
    if np.any(np.isnan(np.array(arr))):
ValueError: could not broadcast input array from shape (256,6,785) into shape (256)
